# Install and configure Certbot
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ certbot_dynamic_defaults }}'
    must_match: yes
  tags: [certbot, always]

- include_tasks: setup-mode-{{ certbot_setup_mode }}.yml
  tags: [certbot, packages]
